### ISSUE TITLE
Unable use search Box

### ISSUE THREAD

**Issue by MrRoxandi** [mrbuilder1961/WheresMyChatHistory#108]
### Description
I have a problem where I am unable to use the search box if I install any other mods that modify the chat in any way.

### How to reproduce
Add a mod that modifies the chat in any way. For example: Symbol Chat

### Log file link
[minecraft logs](https://mclo.gs/K9WBFlH)
### Additional info
`chatlog.json` 
``` json 
{"messages":[],"history":[]} 
```
`chatpatches.json`
``` json
{
  "time": true,
  "timeDate": "HH:mm:ss",
  "timeFormat": "[$]",
  "timeColor": 16733695,
  "hover": true,
  "hoverDate": "MM/dd/yyyy",
  "hoverFormat": "$",
  "hoverColor": 16777215,
  "counter": true,
  "counterFormat": "\u00268(\u00267x\u0026r$\u00268)",
  "counterColor": 16777045,
  "counterCompact": false,
  "counterCompactDistance": 0,
  "boundary": true,
  "boundaryFormat": "\u00268[\u0026r$\u00268]",
  "boundaryColor": 5636095,
  "chatLog": true,
  "chatHidePacket": true,
  "chatWidth": 0,
  "chatMaxMessages": 16384,
  "chatNameFormat": "\u003c$\u003e",
  "shiftChat": 10,
  "messageDrafting": false,
  "searchDrafting": true,
  "hideSearchButton": false,
  "vanillaClearing": false,
  "copyColor": 5636095,
  "copyReplyFormat": "/msg $ "
} 
```
# Mod List
![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/120740818/45e772ed-8488-41ca-98e3-f6b4a8e20949)

**Comment by mrbuilder1961** [comment]
like you can't click or tab to it at all? what about the chat field and the search button, can you interact with those?

**Comment by MrRoxandi** [comment]
I don't know how to get there using TAB, so I can't tell you. I haven't used one of these. I just can't click on that field. The chat field works correctly. The search settings button works as it should too.

**Comment by hexadecimal233** [comment]
I cannot reproduce this with the same mod set in fabric, can you run the same mod set and see if it is resolved?

**Comment by MrRoxandi** [comment]
So, i run it on a fabric with a clear new pack. This issue still there
`mod list`
![image](https://github.com/mrbuilder1961/ChatPatches/assets/120740818/6bfb0d22-8072-42ae-89ef-95173512669d)
`video`
https://github.com/mrbuilder1961/ChatPatches/assets/120740818/d1a7d5a0-5345-4c15-9d94-f033748dca6c

**Comment by mrbuilder1961** [comment]
ok, so the issue is (obviously) that the search field is not registering any clicks. i'm trying to look into the source code of Symbol Chat to see where it registers clicks, but I'm having a hard time with it. @replaceitem, could you let me know where your `mouseClicked` handlers are located so i can move my calls to avoid conflicts? thanks in advance, and sorry about the wait!

**Comment by replaceitem** [comment]
I looked into it, and it looks like this is the fault of symbol chat, since it's preventing any other widget apart from the chat box to be focused

https://github.com/replaceitem/symbol-chat/blob/2a74f24b6329b8f788dc8bd7b1178c111a792ae8/src/main/java/net/replaceitem/symbolchat/mixin/ChatScreenMixin.java#L51-L54

I will change that to only block focusing the symbol panel away from the chatbox.

**Comment by replaceitem** [comment]
Fixed it in https://github.com/replaceitem/symbol-chat/commit/46c7500889d42eba44057740b4a2b6fbdb620119 and tested it with this mod.

**Comment by mrbuilder1961** [comment]
Awesome, thanks so much!! I really appreciate it 😄
that all being said, I can no longer reproduce the issue myself and it appears to be fixed, update should be releasing shortly.
