### ISSUE TITLE
Cant select search bar with BetterAnvil

### ISSUE THREAD

**Issue by KIRUYXAN** [mrbuilder1961/WheresMyChatHistory#148]
### Description
When I try to write something in the search field in chat, it just writes to chat.

### How to reproduce
Open the chat and click on the search field and try to write something

### Expected result
The letters will be written in the search field

### Specs and Details
Required information:
- windows 10 pro
- Mod version 201.5.5
- Fabric version 0.15.7-1.20.1 and API version v0.92.0
- YetAnotherConfigLib version 3.2.2 and Mod Menu version 7.2.2
- Screenshot of all installed mods:
![explorer_g9GBRrx73C](https://github.com/mrbuilder1961/ChatPatches/assets/65653126/55d52701-bc69-4d5a-b72f-102c3a1355cf)

And is it normal that I, on the server, do not have a reply button when I right-click on a message in a chat?

**Comment by mrbuilder1961** [comment]
This might be related to #108, as that had a very similar issue, although that fix should be in the version you're running. About your last message not being able to reply to messages on click, that might be a separate ongoing bug that I will be fixing soon.

If you could provide a video/gif of the issue and a log link, that would be greatly appreciated!

**Comment by KIRUYXAN** [comment]
No, in my case the search field is pressed. And there is no reply button only on servers, because in the single-player world it is there. In the video, I wrote the last messages in a single-player world and before that on the server.
[chatpatches.json](https://github.com/mrbuilder1961/ChatPatches/files/14335222/chatpatches.json)
[chatlog.json](https://github.com/mrbuilder1961/ChatPatches/files/14335263/chatlog.json)
[minecraft.log](https://github.com/mrbuilder1961/ChatPatches/files/14335272/2024-02-19-7.log)

https://github.com/mrbuilder1961/ChatPatches/assets/65653126/c53bd382-bd08-48f3-ae83-22aa42969379

**Comment by mrbuilder1961** [comment]
This is likely unrelated but [in this log that you provided](https://mclo.gs/u8uXmxF), it said there were some compatibility errors you need to resolve. 
![image](https://github.com/mrbuilder1961/ChatPatches/assets/66807297/7d1599d6-efbb-4449-bad3-8e2d48a3c176)

About the actual issue, this is likely due to incompatibility, probably with ChatNotify. If you could try removing it and seeing if the issue persists, and if that doesn't solve it then try running minecraft with *only* Chat Patches and dependencies installed, to isolate the issue. If either of these ideas work, please provide another log on https://mclo.gs! Thanks so much for your patience.

**Comment by KIRUYXAN** [comment]
I tried to remove ChatNotify and ChatHeads, but the search field only worked with Chat Patches and dependencies only, here
[logs](https://mclo.gs/IJDcA40)

**Comment by KIRUYXAN** [comment]
I found a mod that interferes - it's BetterAnvil, I thought that when opening a chat, this mod adds a button to the upper right corner and this may somehow affect the search field, and by disabling it the search field worked

**Comment by mrbuilder1961** [comment]
tysm! i'll look into that as soon as i can

**Comment by mrbuilder1961** [comment]
[the creator responded](https://discord.com/channels/1090757125514461276/1090757891000107069/1210691394587336754) and found the issue but they said they don't have the time to fix it right now. however, i myself can't fix it because the mod overrides anything i do, so for now i think the only viable solution is to not use BetterAnvil or just accept the search bar isn't going to work.

so sorry for this 😣

**Comment by KIRUYXAN** [comment]
no problem, thanks for the help

**Comment by KIRUYXAN** [comment]
Well, apparently BetterAnvil is no longer being developed, so we can don’t wait for a fix
