### ISSUE TITLE
Update to 1.19

### ISSUE THREAD

**Issue by TechPro424** [mrbuilder1961/WheresMyChatHistory#16]

**Comment by TechPro424** [comment]
Wait, when I hover over the label, it says "Will be fixed in the next Minecraft version"
So I have to wait till 1.20?

**Comment by Otifus** [comment]
> Wait, when I hover over the label, it says "Will be fixed in the next Minecraft version" So I have to wait till 1.20?

no, i guess it means the next update of the mod, because what's the point of waiting for 1.20 to make support for 1.19, you know? On curseforge, author noted that he needs to take a short break due to his state of health, so we wish him a speedy recovery, and we can only wait as much as needed :wink:

**Comment by mrbuilder1961** [comment]
By Minecraft version it refers to the Minecraft version of the mod, so "fixed in next version" means the next one of the mod. So currently it's 1.18 so next is 1.19.

It will probably be out soon, but i'm trying to add a few features that are taking longer than expected. i also wanted to add some sort of feature to disable the new chat moderation thing in 1.19+ versions if possible.

**Comment by TechPro424** [comment]
> By Minecraft version it refers to the Minecraft version of the mod, so "fixed in next version" means the next one of the mod. So currently it's 1.18 so next is 1.19.
> 
> It will probably be out soon, but I'm trying to add a few features that are taking longer than expected. If possible, I also wanted to add some feature to disable the new chat moderation thing in 1.19+ versions.

You could check out this mod which disables that chat moderation thing: https://modrinth.com/mod/no-chat-reports
