### ISSUE TITLE
Chat Heads icons disappear - 204.6.4

### ISSUE THREAD

**Issue by nco2k** [mrbuilder1961/WheresMyChatHistory#163]
### Description
[Chat Heads](https://github.com/dzwdz/chat_heads) icons disappear when searching / matching a string.

### How to reproduce
search for a string that matches.

### Expected result
the icons shouldnt disappear.

### Specs and Details
- fabric-api-0.97.0+1.20.4.jar
- chat_heads-0.10.32-fabric-1.20.3.jar
- chatpatches-204.6.4.jar
- YetAnotherConfigLib-3.4.1+1.20.4-fabric.jar
- modmenu-9.2.0-beta.2.jar (725.53 KiB) Primary

![Chat](https://github.com/mrbuilder1961/ChatPatches/assets/26080123/260ba80b-8542-46af-bd1f-eaa43969041a)

**Comment by mrbuilder1961** [comment]
please edit this and replace everything with the filled out bug report template, that's what it's for.

**Comment by mrbuilder1961** [comment]
i'm not sure how easy of a fix this will be, considering chat heads has its own methods to determine which messages are sent by who, and i'm assuming the reason it breaks is because those methods get messed up when the messages are removed.

however, when you search, the way it works is it removes the visible lines associated with messages that don't match the search query, so it can put them back when you're done searching. so that temporary de-sync might mess with it too.

@dzwdz, what do you think? let me know either how heads are placed so i can accomodate, or maybe tell me what you would need to adjust. thanks!

**Comment by mrbuilder1961** [comment]
more info noted in [chat_heads#95](https://github.com/dzwdz/chat_heads/issues/95)

**Comment by mrbuilder1961** [comment]
> more info noted in [chat_heads#95](https://github.com/dzwdz/chat_heads/issues/95)

there used to be more important notes in some issue, i think [chat_heads#83](https://github.com/dzwdz/chat_heads/issues/83) (that's what's linked in the other one), but it leads to a 404, so i guess they deleted the issue? 

i'm going to take that, combined with the original reference being closed, as a signal they don't want to / can't / aren't willing to fix this issue with me. if any new info or related issues come up, please comment them here. in the meantime, i'll close this as **incomplete**.
