### ISSUE TITLE
Chat log crashes w `NoSuchElementException` - 206.6.6 - 1.20.6

### ISSUE THREAD

**Issue by KunKi0827** [mrbuilder1961/WheresMyChatHistory#183]
If i afk a few minute,my game will crash by unknown reason,here is crash report
https://mclo.gs/uh4XhzZ

**Comment by mrbuilder1961** [comment]
should be fixed in [this](https://github.com/mrbuilder1961/ChatPatches/actions/runs/9754245611) build for a temporary fix before `206.6.7` is released! see the readme [here](https://github.com/mrbuilder1961/ChatPatches?tab=readme-ov-file#how-to-access-beta-releases) for instructions on how to test it.

**Comment by KunKi0827** [comment]
Thank you so much! 👍

OBro1961 ***@***.***> 於 2024年7月4日 週四 下午10:36 寫道：

**Comment by mrbuilder1961** [comment]
fixed in 211.6.7!
