### ISSUE TITLE
Suggestion: Search chat history

### ISSUE THREAD

**Issue by EGOIST1372** [mrbuilder1961/WheresMyChatHistory#4]
Hi
can you add Search through chat history? like using RegEx, literal, and case-insensitive (UpperLower-case) 
thanks in advance

**Comment by mrbuilder1961** [comment]
I'll definitely add it to the list of things to implement! IRL life has been busy lately but I think we can make it happen (:

**Comment by EGOIST1372** [comment]
IRL has priority 
take your time
no hurries
thanks <3

**Comment by mrbuilder1961** [comment]
Just an update, this is still planned but again life is busy. Just trying to get all bugs and other minor features done first before I tackle something like this.

**Comment by mrbuilder1961** [comment]
Going to "merge" this with #45. So far, my plan for these suggestions is to add a new menu, a **regex-capable search and replace screen**. ( maybe integrated with YACL ) basically, this screen would allow you to:

- edit an *ordered* list of "Message Modifiers" which apply to all chat messages
- these modifiers are the (psuedo)code equivalent of `chatMessages.forEach(msg -> msg.text.replaceAll(modifierTarget, modifierReplacement)`
- (probably?) be able to target colors/add colors as well
- entire thing is toggleable

I'm not going to try and describe the screen, because ill probably change it a lot and it wont look very good. but just know i am definitely still working on this! Also, almost forgot that I might just add a couple small widgets to the focused chat screen for copying and filtering through messages. it would have regex capabilities and (probably?) color filtering

**Comment by mrbuilder1961** [comment]
i've begun creating this, do you have any specific screen layout in mind? i'm starting with the chat searching menu first and then after i will make a separate screen for message modifications

**Comment by EGOIST1372** [comment]
A suggestion for layout would be the vanilla chat reporting screen when you
want add messages related to the report
But since I have no access to my pc rn I can't offer more but I have more
ideas but need my pc

**Comment by mrbuilder1961** [comment]
ok, i haven't thought of everything yet so this might not work but i'm currently considering adding a search box right in between the chat input box and the chat itself. here are some example images, ignore the messages lol

https://cdn.discordapp.com/attachments/934270816982544387/1075595167890939944/image.png
https://cdn.discordapp.com/attachments/934270816982544387/1075595168096452618/image.png

there's a possibility that i can't fit all the widgets i will need there, but assuming i could, what would you think?

**Comment by EGOIST1372** [comment]
Actually that looks great if the border wasn't red :D
A grey or black border or even transparent would be more subtle
All in all if you can fit all there it would be great

**Comment by mrbuilder1961** [comment]
oh ofc that was just a fast mock-up, it would probably be gray and semi transparent

**Comment by Bswuave** [comment]
oh wow I just suggested this on curse, glad more people want this feature !

**Comment by mrbuilder1961** [comment]
okay, for searching parameters how is "case sensitive", "regex", and "modifiers"? (modifiers allows for matching against specific colors, there will be a detailed tooltip!)

**Comment by mrbuilder1961** [comment]
this is almost done, i just need to polish some more stuff and do a 1.19.4 hotfix first (:

**Comment by mrbuilder1961** [comment]
this is like 95% done but im gonna give it a couple more days to make sure i don't forget anything important 😁

**Comment by Bswuave** [comment]
> this is like 95% done but im gonna give it a couple more days to make sure i don't forget anything important 😁

excited to see ! it will be so much easier to find peoples messages now in chat 👯

**Comment by EGOIST1372** [comment]
@mrbuilder1961 Hey there
Long time no see
Didn't wanted to distract you
Since last time I was around u did amazing job on this mod and now its THE best chat mod for Minecraft
Just wanted to thank you
