### ISSUE TITLE
Search option - 194.4.4

### ISSUE THREAD

**Issue by NoltoxGit** [mrbuilder1961/WheresMyChatHistory#81]
### Description
Since the last update, the option in ModMenu to disable search in chat no longer works.

### Expected result
That the magnifying glass to search something in the chat, does not appear when you open the chat.

### Log file link
[Log.](https://mclo.gs/Et896QD)

### Specs and Details
Required information:
- Windows 11
- 194.4.4
- Fabric 0.14.19 & FabricAPI 0.79.0
- YetAnotherConfigLib 2.50 & Mod Menu 6.2.2
- [List of all installed mods](https://prnt.sc/-NshVVOHQnnl)

Optional but suggested information:
- `chatpatches.json` [pastebin file](https://pastebin.com/PBCWWu0J)
- `chatlog.json` [pastebin file](https://pastebin.com/pEpZx2MW)

**Comment by mrbuilder1961** [comment]
i didn't find anything immediately wrong in the log file, could you send a screenshot and your config file please?

**Comment by ItzSkyReed** [comment]
![image](https://user-images.githubusercontent.com/93844414/235481685-53de4d88-5805-4855-bc0c-dcb12bb2b5b8.png)
![image](https://user-images.githubusercontent.com/93844414/235481820-e02886a2-6183-4e3a-9ff6-5d7eef48f47c.png)
[chatpatches.zip](https://github.com/mrbuilder1961/ChatPatches/files/11366408/chatpatches.zip)
zip because json is not supported by github
